### ISSUE TITLE
System Crash After 32 Game Launches

### ISSUE THREAD

**Issue by vardrop** [Reisyukaku/NX_Sysmodules#12]
[ReiNX#38](https://github.com/Reisyukaku/ReiNX/issues/38)

this error was apparently fixed in [Atmosphere 0.7.4](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.7.4)

**Comment by gr3ger** [comment]
And this is the commit to Atmosphere that supposedly fixed it.
Atmosphere-NX/Atmosphere@ce1a6a6

**Comment by Reisyukaku** [comment]
181be18db8127b9879d79dd15d2100c8220c1931
