### ISSUE TITLE
Update libstratosphere

### ISSUE THREAD

**Issue by RShadowhand** [Reisyukaku/NX_Sysmodules#13]
Currently, ldn_mitm.kip can't be used in ReiNX without a special build.
Updating libstratoshphere to [05015b9](https://github.com/Atmosphere-NX/libstratosphere/tree/05015b9354d3df80e0836aa95d1d4dcfc2aef4b7) will alleviate this problem.

**Comment by spacemeowx2** [comment]
Exactly, updating `sm` is needed.

https://github.com/Atmosphere-NX/Atmosphere/blob/46cc08160d86eef9a63dc0eb1994871b1f770f62/stratosphere/sm/source/sm_user_service.hpp#L31

**Comment by Reisyukaku** [comment]
Thanks for the heads up. By the looks of it, you'd need to run exo with reinx for this to work, which is doable of course but a minor inconvenience.

**Comment by Reisyukaku** [comment]
Done
