### ISSUE TITLE
Preserve upstream history

### ISSUE THREAD

**Issue by roblabla** [Reisyukaku/NX_Sysmodules#3]
I've done the work at https://github.com/roblabla/NX_Sysmodules

This is better for multiple reasons:

1. It makes it easy to know what commit the fork is based on
2. It makes it easy to cherry-pick upstream commits downstream
3. It makes it easy to see what the changes are.

This was done by using `git filter-branch --prune-empty --subdirectory-filter stratosphere/` and then manually reapplying the commit from NX_Sysmodules.

I can't submit a pull request because the branches don't share an initial commit. If you want to use it, you'll have to clone my branch, and `git push --force` it to this repo.

**Comment by Reisyukaku** [comment]
~~hmm.. interesting. I do like this idea, but  god knows ill just end up breaking everything trying to cherry pick new commits. I hate git most of the time. I'll try sometime though i guess.~~
Edit: woo, i did it! lol
